### ISSUE TITLE
Crash - Android - OpenGL

### ISSUE THREAD

**Issue by daldegam** [effekseer/Effekseer#906]
I have some crashes happening on some Android devices.
I can't reproduce the crash, but I have hundreds of reports in Firebase Crashlytics.

The details I have are:

Version I'm using: `161c`

Location: `[EffekseerRenderer.StandardRenderer.h:918]`

backtrace:
```
  #00  pc 0x00000000000706d8  /apex/com.android.runtime/lib64/bionic/libc.so (memcpy+280)
  #01  pc 0x000000000012ee50  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!77df12deb6a622478efa8fb9929034!8c08135!+968)
  #02  pc 0x0000000000759a60  [...].so (EffekseerRenderer::StandardRenderer<EffekseerRendererGL::RendererImplemented, EffekseerRendererGL::Shader>::Rendering_(Effekseer::SIMD::Mat44f const&, Effekseer::SIMD::Mat44f const&, int, int, int, int, EffekseerRenderer::StandardRendererState const&)+918)
  #03  pc 0x00000000007586bc  [...].so (EffekseerRenderer::StandardRenderer<EffekseerRendererGL::RendererImplemented, EffekseerRendererGL::Shader>::Rendering()+503)
  #04  pc 0x00000000007568bc  [...].so (EffekseerRendererGL::RendererImplemented::EndRendering()+422)
```

The crash happens on devices with different versions of android, from 5 to 12.

I know I'm using a slightly old version, I'll update to 1.70 to see if that fixes it.

But anyway, I thought I'd better report it to see if it's something still unknown.

If you have anything I can provide to clarify what it could be, let me know.

Thanks

**Comment by durswd** [comment]
It seems that the error occurs with glDrawElements.
I need more detail or an environment where I reproduce the error.

**Comment by durswd** [comment]
What the maximum number of sprite do you set?

https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/EffekseerRendererGL/EffekseerRendererGL.h#L642
squareMaxCount

**Comment by durswd** [comment]
I checked release notes and I didn't find a log to fix this bug. But OpenGL renderer was changed in current master branch. It is possible that the bug has been fixed.

**Comment by daldegam** [comment]
Hello! A long time has passed. I did some tests with effekseer in production.
I'm using version 1.70e, and the crash still persists.

Regarding the squareMaxCount number, I am using 4000.

I initialize the renderer like this:
`auto renderer = ::EffekseerRendererGL::Renderer::Create(4000, EffekseerRendererGL::OpenGLDeviceType::OpenGLES3);`

When the device uses OpenGL2 I do not initialize Effekseer.

Sorry for the long delay.
I will respond in time now.

Thanks.

**Comment by durswd** [comment]
Please check it on 1.80.3
