### ISSUE TITLE
cmake install missing header file？

### ISSUE THREAD

**Issue by lty123456** [effekseer/Effekseer#965]
i try to import Effekseer though: find_package
first, i use vs2022 cmake open the Effekseer  and install Effekseer,
second, import and link it like:
--------------------
list(APPEND CMAKE_PREFIX_PATH D:/Project/3rdparty/Effekseer/out/install/x64-Debug/lib/cmake)
find_package(Effekseer REQUIRED)
find_package(EffekseerRendererCommon REQUIRED)
target_link_libraries(myproject Effekseer EffekseerRendererCommon)
-------------------------

all above steps are ok in vs cmake check,but when i try compile my project i get error:  C1083 : a lists header files missing
here is the missing lists my compiler report:
Effekseer.Base.h
Effekseer.InternalStruct.h
Effekseer.Random.h
Float4.h
Effekseer.Math.h
Int4.h
EffekseerRendererFlags.h
Effekseer.CompiledMaterial.h
BinaryVersion.h
Effekseer.MaterialCompiler.h
Effekseer.MaterialFile.h
SplineGenerator.h
then i try add these files to they cmake variable "effekseer_public_h" and install again ,now C1083 error gone.
is that you forgot install these files?

headers missing resovled,but new error reported: LNK1104 libpng16_staticd.lib not  found
must i install libpng,i thing Effekseer have contain libpng internal,or something wrong i made,can you give me some advice

**Comment by lty123456** [comment]
another  issues maybe below(i put it here because it's appers in one require i need:add Effekseer EffekseerRendererCommon to my cmake project and build and install my project and it's depends):
    when i install my project i also install Effekseer EffekseerRendererCommon target by my cmakelists.txt,because Effekseer default install dir is not i desire,so i get error when install:
  CMake Error at cmake_install.cmake:256 (file):
    file INSTALL cannot find "D:/Project/ZSpace/EffekseerRenderer.Renderer.h"

    as you see,install process EffekseerRendererCommon header "EffekseerRenderer.Renderer.h" from my project(ZSpace),
i try to instead EffekseerRendererCommon/CMakeLists.txt :
set(PublicHeaders
    EffekseerRenderer.Renderer.h ...)
to 
file(GLOB PublicHeaders
    EffekseerRenderer.Renderer.h ...)
and it's ok for me now,i'm not sure it's a issue or my poor use,may be you need its

**Comment by durswd** [comment]
We don't support find_package(Effekseer)

**Comment by durswd** [comment]
I'm fixing now
https://github.com/effekseer/Effekseer/pull/966

**Comment by durswd** [comment]
I fixed it.

**Comment by lty123456** [comment]
Second issue: file INSTALL cannot find "D:/Project/ZSpace/EffekseerRenderer.Renderer.h" still exist?

**Comment by lty123456** [comment]
second issue happend when i use add_subdirectroy because i don't want process libpng,then i cat not add Effekseer EffekseerCommonRender to my export set（i want install all deps and my project to install/ dir） because cmake error:

includes target "EffekseerRendererCommon" which requires target "Effekseer" that is not in this export set, but in multiple other export sets: lib/cmake/Effekseer-config.cmake
So i install Effekseer EffekseerRenderCommon target direct and add find_dependcy in my xxxConfig.cmake.in,and  comment abovt instead set to file
it's work for me,but i think actually cumbersome，if i can add all denpends to my export set it much simple

**Comment by durswd** [comment]
libpng is off in defalt settings.
Please read our test

https://github.com/effekseer/Effekseer/tree/master/Script/Test_Install

**Comment by lty123456** [comment]
ok,may be my wrong settings somewhere
